config/routes.rb
ActivityTracking::Application.routes.draw do
  resources :categories

  devise_for :users

  root :to => "categories#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.xml
  before_filter :authenticate_user!
  def index
    @categories = Category.search(params[:search]).paginate(:page => params[:page], :per_page => 100)
    if @categories.blank?
      @categories = Category.paginate(:page => params[:page], :per_page => 100)
      # @search_blank = true
    end
    respond_to do |format|
      format.js
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    #@category = Category.find(params[:id])
    @search = Category.find(params[:id])
    @category = Category.where("title = ?", @search.title)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :date %>
    <%= f.input :title, :label => 'Category', :input_html => {:class => "title_input"} %>
    <%= f.input :information, :label => 'Info    ', :input_html => { :cols => 30, :rows => 10 } %>
    <%= f.input :tag, :label => 'Tags    ', :input_html => { :cols => 30, :rows => 10 } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>  <%= link_to 'Cancel', categories_path %>
  </div>
<% end %>

app/views/categories/_list.html.erb
<p class="notification">
  sorry, your search not exist
</p>
<div>
    <% @categories.each do |category| %>
      <div style="margin-right: 10px; width:90px; float: left; line-height: 22px;">
        <%= link_to "#{category.title}", category %>
      </div>
    <% end %>
</div>

<%= will_paginate @categories %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1 style="padding-top: 20px; padding-bottom: 10px;">Listing categories</h1>

<div style="margin-bottom: 20px;">
  <div >

    <%= form_for :search, :url => { :action => "index" }, :html => { :method => "get", :remote => true } do |f| %>
          <%#= f.label :name_contains %>
          <%= f.text_field :title_or_tag_or_information_contains %>
          <%= f.submit "Search" %>
    <% end %>

  </div>
  <div>
    <%= link_to 'New Category', new_category_path %>
  </div>
</div>

<div id="list">
  <%= render "list"  %>
</div>

app/views/categories/index.js.erb
$("#list").html('<%= escape_javascript(render "list") %>');

app/views/categories/new.html.erb
<h1 style="padding-top: 20px; padding-bottom: 10px;">New Record Entry Screen</h1>

<%= render 'form' %>

<%#= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1 style="padding-top: 20px; padding-bottom: 10px; font-size: 36px; color: #00A6EC;"><%= @category.first.title.upcase %></h1>

<table id="category-table">
  <tr>
    <th></th>
    <th></th>
    <th>Date</th>
    <th>Information</th>
  </tr>
  <% @category.each do |category| %>
      <tr>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category_url(category) , :confirm => 'Are you sure?', :method => :delete %></td>
        <td><%= category.date %></td>
        <td><%= category.information %></td>
      </tr>
  <% end %>

</table>

<%= link_to 'Back', categories_path %>

app/views/layouts/_css.erb
<%= stylesheet_link_tag 'reset',:media=>:all   %>
<%= stylesheet_link_tag 'application' %>


<%= stylesheet_link_tag 'show', :media=>:all   %>
<%= stylesheet_link_tag 'simple_form',:media=>:all   %>

app/views/layouts/_footer.html.erb
<footer>
      <span>Copyright &copy; OZZLIST. All Rights Reserved.</span>
</footer>

app/views/layouts/_header.html.erb
<header >
      <hgroup id="menu-grey">
        <a title="Activity Tracking" href="/" id="logo">Ozzlist</a>
        
        
      </hgroup>
</header>

app/views/layouts/_js.erb
<%= javascript_include_tag :defaults %>
<%= javascript_include_tag 'application' %>

app/views/layouts/_menu.erb
<nav id="main-tabs">
  <ul class="tabs">
    
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActivityTracking</title>
    <%= render :partial=>'/layouts/css' %>
    <%= yield :css %>
    <%= csrf_meta_tag %>
    <%= render :partial=>'/layouts/js' %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <section class="container">
        <%= render :partial=>'/layouts/header' %>
        <section class="main">
          <%= yield :header %>
          <%= yield %>
        </section>
      <%= render :partial => "layouts/footer" %>
      <%= yield :js %>
    </section>
  </body>
</html>